"""initial

Revision ID: 499535e395ea
Revises: 
Create Date: 2026-03-04 16:53:59.343946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499535e395ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('final_capital', sa.Float(), nullable=False),
    sa.Column('total_return_pct', sa.Float(), nullable=True),
    sa.Column('annualized_return_pct', sa.Float(), nullable=True),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('sortino_ratio', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('win_rate_pct', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('avg_win', sa.Float(), nullable=True),
    sa.Column('avg_loss', sa.Float(), nullable=True),
    sa.Column('rr_ratio', sa.Float(), nullable=True),
    sa.Column('trades_detail', sa.JSON(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_id'), 'backtest_results', ['id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('signal', sa.Enum('BUY', 'SELL', 'SHORT', 'COVER', 'HOLD', name='signaltype'), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('regime', sa.String(length=50), nullable=True),
    sa.Column('asset_class', sa.Enum('CRYPTO', 'STOCK', 'OPTION', name='assetclass'), nullable=False),
    sa.Column('broker', sa.Enum('BINANCE', 'ALPACA', 'IBKR', name='brokername'), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('acted_on', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_class', sa.Enum('CRYPTO', 'STOCK', 'OPTION', name='assetclass'), nullable=False),
    sa.Column('broker', sa.Enum('BINANCE', 'ALPACA', 'IBKR', name='brokername'), nullable=False),
    sa.Column('execution_mode', sa.Enum('SUGGESTION', 'SEMI_AUTO', 'FULL_AUTO', name='executionmode'), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_strategies_id'), 'strategies', ['id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'FILLED', 'CANCELLED', 'REJECTED', name='orderstatus'), nullable=False),
    sa.Column('execution_mode', sa.Enum('SUGGESTION', 'SEMI_AUTO', 'FULL_AUTO', name='executionmode'), nullable=False),
    sa.Column('broker', sa.Enum('BINANCE', 'ALPACA', 'IBKR', name='brokername'), nullable=False),
    sa.Column('asset_class', sa.Enum('CRYPTO', 'STOCK', 'OPTION', name='assetclass'), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('strategy_name', sa.String(length=100), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_strategies_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_backtest_results_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
